Website = "https://patenaude.io/"

[Details]
  Icon = "Icon.png"
  Name = "KarmaManager"
  ID = "io.patenaude.karmamanager"
  Version = "0.8.0"
  Build = 285

[LinuxAndBSD]
  GenericName = "Anagram Maker"
  Categories = ["Game"]
  Comment = "Make Anagrams"
  Keywords = ["game"]
