Website = "https://patenaude.io/"

[Details]
  Icon = "Icon.png"
  Name = "KarmaManager"
  ID = "io.patenaude.karmamanager"
  Version = "0.0.2"
  Build = 43

[LinuxAndBSD]
  GenericName = "Anagram Maker"
  Categories = ["Game"]
  Comment = "Make Anagramss"
  Keywords = ["game"]
