#!/bin/bash

source .env 

case "$1" in 
	android)
		fyne package --target android
		fyne install --os android
		;;
	ios)
		fyne release --target ios --certificate "${IOSDEVCERT}" --profile "${IOSDEVPROF}"
		DEVICE=$(xcrun devicectl list devices 2>&1 | awk 'NR>2 && /connected/ && /iPhone/ {print $3; exit}')
		if [ -z "$DEVICE" ]; then
			echo "No connected iPhone found"
			exit 1
		fi
		xcrun devicectl device install app --device "$DEVICE" KarmaManager.ipa
		;;
	iossimulator)
		fyne release --target ios --certificate "${IOSDEVCERT}" --profile "${IOSDEVPROF}"
		fyne install --os iossimulator
		;;
	*)
		echo Only android, ios and iossimulator supported currently
		;;
esac	
